name: EBAC exercício CI

on:
  push:
    branches: [ ci ]

  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Cypress run
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          install-command: npm install
          browser: electron
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report
          
        

    
  
